name: CI

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "gradle.properties"
  pull_request:
    paths-ignore:
      - "gradle.properties"

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Test and build runtime jar
        run: ./gradlew test runtimeJar
